import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/global.css";
import AuthProvider from "./auth-context";
import StatusBar from "./components/status-bar";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gerbang Suara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
